Enable local shell in remote directories
Stunkymonkey/nautilus-open-any-terminal pull request #145
Opened 2024-03-03 07:45 UTC by human9

Thanks for this nice extension!

When browsing a remote location in nautilus, the native open terminal context menu option gives you the option to open a local or remote terminal:

![screeny](https://github.com/Stunkymonkey/nautilus-open-any-terminal/assets/18050721/a6e20855-d39f-4748-bff4-30aa6e2059ba)

I find this pretty useful so this pull request attempts to replicate this behavior within nautilus-open-any-terminal.

If this feature is something that you would consider merging I am happy to make any required changes. I think it could be cleaned up a bit at least.

2024-03-03 08:07 UTC, lvxnull commented
I wouldn't mind adding this feature, but I'd rather have the local option be "open in local terminal" rather than "open in terminal" if the remote option is present as well. This would require updating the translation files.

2024-03-03 23:26 UTC, human9 commented
I agree that would be preferable. I can update the code, unfortunately I am unable to translate the human languages, unless you're happy with a machine translation.

2024-03-03 23:32 UTC, lvxnull commented
I meant that in a "this project must have the translations updated" sense, rather than "you must update the translations". I can update the Polish translation immediately after this is merged, @Stunkymonkey could update the German one, but im not sure how long it would take to get 100% translation coverage again.

2024-03-03 23:39 UTC, human9 commented
I understand, in that case I'll just update the pull request to make the code changes.

2024-03-04 05:52 UTC, human9 commented
Here's how right click on a remote dir now looks:

![file](https://github.com/Stunkymonkey/nautilus-open-any-terminal/assets/18050721/6b165761-ef15-4421-a0b1-fc5749dc1db6)

And for clicking in the background of a remote dir:

![back](https://github.com/Stunkymonkey/nautilus-open-any-terminal/assets/18050721/ca22efdd-6d73-41f1-986a-036dd798a66c)

2024-03-04 07:02 UTC, human9 commented
One thing I'm not sure about here is the shortcut key, I just set it to always open a local terminal but that might not be what people want.

2024-03-04 09:51 UTC, lvxnull commented
maybe we could have a setting that determines if the keybind opens a remote terminal when possible

2024-03-04 10:43 UTC, lvxnull requested changes
This breaks translations. Please hardcode the string and pass it to the `_` function instead of programmatically constructing it.

2024-03-04 22:49 UTC, human9 commented
I see, I've replicated with hardcoded strings this time.

2024-03-04 23:33 UTC, human9 commented
And a commit adding a setting that can toggle the shortcut to be local or remote. Let me know if that looks okay.

2024-03-04 23:37 UTC, lvxnull commented
Looks ok at a first glance, I'll check more thoroughly tommorow.

2024-03-05 11:27 UTC, lvxnull approved these changes
My only complaint would be the length of `get_file_items` and `get_background_items` methods. Overall LGTM.

2024-03-08 04:05 UTC, human9 commented
Sorry for delayed response. re: length, I'm open to suggestions. One thing that would definitely reduce required code would be to accept a single naming strategy for both file and background items.

i.e., currently this is the naming for files:
~~~
Open In Remote {}
Open In Local {}
Open In {}
~~~
and for background:
~~~
Open Remote {} Here
Open Local {} Here
Open {} Here
~~~

I think the file naming scheme would work for both file and background.
But maybe that could be a separate pull request.

2024-03-08 21:15 UTC, lvxnull commented
I have an idea on how to shorten the logic of these methods, but let's focus on merging this PR first.

2024-03-09 23:26 UTC, Stunkymonkey commented
can you please fix the conflicts?

i will think about shortening tomorrow.

2024-03-09 23:39 UTC, lvxnull submitted a review, later dismissed

2024-03-09 23:48 UTC, lvxnull approved these changes

2024-03-09 23:48 UTC, merged